# Generated by Django 5.1.5 on 2025-02-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=50)),
                ('doctor', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=50)),
                ('phn', models.IntegerField()),
                ('smpt', models.CharField(max_length=100)),
            ],
        ),
    ]
