# Generated by Django 5.1.5 on 2025-02-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='bloodbank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bloodtype', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('firsttime', models.CharField(max_length=50)),
            ],
        ),
    ]
