# Generated by Django 5.1.5 on 2025-02-12 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_bloodbank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodbank',
            name='firsttime',
        ),
    ]
