# Generated by Django 5.1.6 on 2025-02-12 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_remove_bloodbank_firsttime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Firstname',
            new_name='firstname',
        ),
        migrations.RemoveField(
            model_name='bloodbank',
            name='bloodtype',
        ),
    ]
